[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 0, y = 0 }

[font]
normal = { family = "ZedMono Nerd Font", style = "Medium" }
bold = { family = "ZedMono Nerd Font", style = "Bold" }
italic = { family = "ZedMono Nerd Font", style = "Italic" }
bold_italic = { family = "ZedMono Nerd Font", style = "Bold Italic" }
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.30
blink_interval = 200
blink_timeout = 0

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[general]
live_config_reload = true
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  #"~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[terminal]
