# Font
font_family      ZedMono NF Medium
bold_font        ZedMono NF Bold
italic_font      ZedMono NF Italic
bold_italic_font ZedMono NF Bold Italic
font_size        12.6

# Cursor
cursor_shape             beam
cursor_thickness         0.3
cursor_blink_interval    0.25
cursor_stop_blinking_after 0
cursor                   #d4a800
cursor_text_color        #faf4ff

# Window
background_opacity       1
hide_window_decorations  yes
window_padding_width     0

# Mouse
mouse_hide_wait          1.2

# Selection
copy_on_select           yes

# Misc
repaint_delay            10
input_delay              3
sync_to_monitor          yes
visual_bell_duration 0.0
enable_audio_bell no
disable_ligatures always

include rose-pine-moon.conf
