[Main]
ignore_audio = false
wait_before_sleep = true
disable_automatic_dpms_activation = true
disable_screensaver = true

[Action dim]
# Dim the screen after 10 minutes, restore the original brightness
# when activity resumes
trigger = timeout 600
exec = builtin:dim
resume_exec = builtin:undim

[Action turn off monitor]
# Turn off the monitor after 11 minutes, turn it back on when
# activity resumes
trigger = timeout 660
exec = xset dpms force off
resume_exec = xset dpms force on

[Action suspend]
# Suspend the computer after 20 minutes of inactivity
trigger = timeout 1200
exec = builtin:suspend

[Action lock]
# Run custom scripts when the session is locked or unlocked
trigger = lock
exec = betterlockscreen -l dimblur
resume_exec = true
